# -*- mode: ruby -*-
# vi: set ft=ruby :

## This Vagrant file uses the default virtual machine, virtualbox

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "vagrant.sh"
  config.vm.network "forwarded_port", guest: 8787, host: 8080
end
