# -*- mode: ruby -*-
# vi: set ft=ruby :

## Use vagrant to facilitate deploying the docker container cross-platform
## This Vagrant file uses the default virtual machine, virtualbox, to provide the linux environment
##
## USAGE:
##     vagrant up
## Then point your browser to http://192.168.33.10:8787
## Log into RStudio using the user:pw combination rstudio:rstudio

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.3"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "boot2docker"
  config.vm.box = "yungsang/boot2docker"

  ## Configure this appropriately based on the host machine capability and how much of it you want to allocate.
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

#  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant"


  ## Adjust datetime after suspend and resume
  config.vm.provision :shell do |s|
    s.inline = <<-EOT
      sudo /usr/local/bin/ntpclient -s -h pool.ntp.org
      date
    EOT
  end

  config.vm.provision :docker do |d|
    d.pull_images "cboettig/rstudio"
    d.run "cboettig/rstudio",
      args: "-p 8787:8787"
  end

  config.vm.network :forwarded_port, guest: 8787, host: 8888
end
