# -*- mode: ruby -*-
# vi: set ft=ruby :



## Launch with:
##     vagrant up --provider=docker
## Visit http://localhost:8787 in your browser and log into rstudio with user:pw rstudio:rstudio

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
    d.image = "cboettig/ropensci"
    d.ports = ["8787:8787"]
    d.remains_running = true
#    d.volumes = "$(pwd):/host"
 #  d.name = vagrantdocker
  end
  config.vm.network "forwarded_port", guest: 8787, host: 8787
end


